image: alpine:3.19

variables:
  TF_VERSION: "1.9.8"
  ARM_CLIENT_ID: $ARM_CLIENT_ID
  ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
  ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
  ARM_TENANT_ID: $ARM_TENANT_ID

stages:
  - prepare
  - init
  
before_script:
  - apk add --no-cache curl unzip bash
  - curl -sLo terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform.zip && mv terraform /usr/local/bin/
  - terraform version
  - echo "provider credentials loaded"

prepare:
  stage: prepare
  script:
    - echo "Preparation done"

init:
  stage: init
  script:
    - terraform init
    - terraform plan -out=tfplan
    - terraform show -no-color tfplan
    - terraform apply -auto-approve tfplan


